# coder_config.yml

provider: "anthropic"
model: "claude-3-opus-20240229"
temperature: 0
env_var: "ANTHROPIC_API_KEY"
api_base: "https://api.anthropic.com"

project_path: "tests/test_projects/project1"

input_data: |
  @@ -9,9 +9,11 @@ logger = logging.getLogger(__name__)

  def process_user(user_data):
      """Process user data and return formatted string"""
  +    logger.debug(f"Processing user data: {user_data}")
      name = format_name(user_data["name"])
      age = validate_age(user_data["age"])
  -    return f"{name} is {age} years old"
  +    result = f"{name} is {age} years old"
  +    logger.debug(f"Processed result: {result}")
  +    return result

  if __name__ == "__main__":
      test_data = {

instruction: |
  Extract changes from the input maintaining:
  1. Original file paths from the diff
  2. Change type (modify/create/delete)
  3. Description of changes
  4. Complete diff patches
  
  Return each change as a JSON object with exact fields:
  {
    "file_path": "tests/test_projects/project1/sample.py",
    "type": "modify", 
    "description": "Adding logging functionality",
    "diff": "git style diff contents"
  }

format: "json"
merge_method: "smart"
