# coder_config.yml

provider: "anthropic"
model: "claude-3-opus-20240229"
temperature: 0
env_var: "ANTHROPIC_API_KEY"
api_base: "https://api.anthropic.com"

# Base path where files are located
project_path: "tests/test_projects/project1"

input_data: |
  Let's add logging to all functions. Here are the changes:

  For tests/test_projects/project1/sample.py:
  ```python
  import logging

  logging.basicConfig(level=logging.INFO)
  logger = logging.getLogger(__name__)

  def greet(name):
      logger.info(f"Greeting user: {name}")
      print(f"Hello, {name}!")

  def calculate_sum(numbers):
      logger.debug(f"Calculating sum of numbers: {numbers}")
      result = sum(numbers)
      logger.info(f"Sum calculated: {result}")
      return result

  if __name__ == "__main__":
      greet("World")
      print(calculate_sum([1, 2, 3, 4, 5]))
  ```

instruction: |
  Extract code changes from the input. Each code block represents changes for a specific file.
  For each change provide a JSON object with:
  - file_path: The complete path to the file relative to project_path
  - content: The complete new file content
  - type: "modify" for updating existing files
  - description: Brief description of the changes

format: "json"
merge_method: "smart"