# Corrected c4h_config.yml
# Only includes parameters that are actually implemented

project:
  default_path: "/Users/jim/src/apps/c4h_ai_built_coder"  # Root of the project
  workspace_root: "workspaces"

runtime:
  max_iterations: 3
  intent:
    description: "Review testharness.py. Do not lose any existing functionality in testharness.py. testharness dumps out the results just change the output format."

llm_config:
  agents:
    discovery:
      tartxt_config:
        input_paths: 
          - "src"
        exclusions:
          - "**/__pycache__/**"
          - "**/.pytest_cache/**"
          - "**/*.pyc"
          - "**/.git/**"
        output_type: "stdout"
        output_file: null  # Only used if output_type is "file"

backup:
  enabled: true
  path: "workspaces/backups"

logging:
  level: "INFO"
  format: "structured"
