# App-specific configuration that matches AppConfig model
provider: "anthropic"
model: "claude-3-opus-20240229"
temperature: 0

# Required for processing
input_data: ""  # Will be populated by CLI during execution
instruction: ""  # Will be populated by CLI during execution
format: "json"
merge_method: "smart"

# Project configuration
project_path: "tests/test_projects/project1"

# Additional settings preserved from previous config
project:
  default_path: "tests/test_projects/project1"
  workspace_root: "workspaces"
  max_file_size: 1048576

runtime:
  merge_strategy: "smart"
  max_iterations: 3
  backup_enabled: true

intent:
  description: "Add logging to all functions and methods"
  scope: ["*.py"]

logging:
  level: "INFO"
  format: "structured"