# config/system_config.yml

llm_config:
  default_provider: "anthropic"
  default_model: "claude-3-opus-20240229"
  
  agents:
    discovery:
      provider: "anthropic"
      model: "claude-3-haiku-20240307"  # Fastest for file analysis
      temperature: 0
      
    solution_designer:
      provider: "anthropic"
      model: "claude-3-opus-20240229"  # Most capable for complex decisions
      temperature: 0
    
    coder:
      provider: "anthropic"
      model: "claude-3.5-sonnet-20241022"  # Balance of speed and capability
      temperature: 0
      
    assurance:
      provider: "anthropic"
      model: "claude-3-haiku-20240307"  # Fast for validation checks
      temperature: 0

backup:
  enabled: true
  path: "workspaces/backups"
  max_backups: 5

logging:
  level: "INFO"
  format: "structured"