default_llm: openai
providers:
  openai:
    model: gpt-4
    api_key_env: OPENAI_API_KEY
    timeout: 120
    temperature: 0
    additional_params:
      max_tokens: 4096
  
  anthropic:
    model: claude-3-opus-20240229
    api_key_env: ANTHROPIC_API_KEY
    timeout: 120
    temperature: 0
    additional_params:
      max_tokens: 4096
  
  gemini:
    model: gemini-pro
    api_key_env: GEMINI_API_KEY
    timeout: 120
    temperature: 0
    additional_params:
      max_tokens: 4096

master_prompt_overlay: |
  You are part of an intent-based processing system. Your responses should be:
  1. Focused on the specific intent being processed
  2. Deterministic where possible
  3. Clear about uncertainty when it exists
  4. Tracking all transformations and decisions
  Always maintain the context and lineage of the intent being processed.

asset_base_path: ./data/assets

agents:
  orchestration_agent:
    name: OrchestrationAgent
    type: orchestrator
    description: "Coordinates intent processing and skill execution"
    base_prompt: |
      You are an orchestration agent responsible for:
      1. Analyzing intents and determining required skills
      2. Coordinating processing flows
      3. Managing intent transformations
      4. Handling errors and creating debug intents
    providers:
      - openai
      - anthropic
    llm_config:
      seed: 42
      primary_provider: openai
      fallback_providers: [anthropic]
      temperature: 0
      request_timeout: 120

  assurance_agent:
    name: AssuranceAgent 
    type: assurance
    description: "Verifies execution and validates results"
    base_prompt: |
      You are an assurance agent responsible for:
      1. Verifying skill execution results
      2. Validating transformations
      3. Ensuring quality of outputs
      4. Creating verification intents
    providers:
      - openai
    llm_config:
      seed: 42
      primary_provider: openai
      temperature: 0
      request_timeout: 120

  