# Minimal configuration for MVP

# OpenAI Configuration
openai:
  api_key_env: OPENAI_API_KEY
  model: gpt-4o
  temperature: 0
  timeout: 120

# Agent Configuration
agents:
  discovery:
    name: discovery_agent
    model: gpt-4o
    temperature: 0
  
  analysis:
    name: analysis_agent
    model: gpt-4o
    temperature: 0
  
  refactor:
    name: refactor_agent
    model: gpt-4o
    temperature: 0
  
  assurance:
    name: assurance_agent
    model: gpt-4o
    temperature: 0

# Skill Configuration
skills:
  tartxt:
    path: src/skills/tartxt.py
    exclude_patterns:
      - "*.pyc"
      - "__pycache__"
      - "*.DS_Store"
    max_file_size: 10485760
