# config/system_config.yml

providers:
  anthropic:
    api_base: "https://api.anthropic.com"
    context_length: 200000
    env_var: "ANTHROPIC_API_KEY"
  openai:
    api_base: "https://api.openai.com/v1"
    context_length: 128000
    env_var: "OPENAI_API_KEY"
  gemini:
    api_base: "https://generativelanguage.googleapis.com/v1beta"
    context_length: 32000
    env_var: "GEMINI_API_KEY"

llm_config:
  default_provider: "anthropic"
  default_model: "claude-3-opus-20240229"
  
  agents:
    discovery:
      provider: "anthropic"
      model: "claude-3-haiku-20240307"
      temperature: 0
      
    solution_designer:
      provider: "anthropic"
      model: "claude-3-opus-20240229"
      temperature: 0
    
    coder:
      provider: "anthropic"
      model: "claude-3.5-sonnet-20241022"
      temperature: 0
      
    assurance:
      provider: "anthropic"
      model: "claude-3-haiku-20240307"
      temperature: 0

project:
  default_path: "tests/test_projects/project1"
  default_intent: "Add logging to every function, replace all prints with logs"
  workspace_root: "workspaces"
  max_file_size: 1048576

backup:
  enabled: true
  path: "workspaces/backups"
  max_backups: 5

logging:
  level: "INFO"
  format: "structured"