# config/system_config.yml

providers:
  anthropic:
    api_base: "https://api.anthropic.com"
    context_length: 200000
    env_var: "ANTHROPIC_API_KEY"
  openai:
    api_base: "https://api.openai.com/v1"
    context_length: 128000
    env_var: "OPENAI_API_KEY"
  gemini:
    api_base: "https://generativelanguage.googleapis.com/v1beta"
    context_length: 32000
    env_var: "GEMINI_API_KEY"

llm_config:
  default_provider: "anthropic"
  default_model: "claude-3-opus-20240229"
  
  agents:
    discovery:
      provider: "anthropic"
      model: "claude-3-haiku-20240307"
      temperature: 0
      prompts:
        system: |
          You are a project discovery agent.
          You analyze project structure and files to understand:
          1. Project organization
          2. File relationships
          3. Code dependencies
          4. Available functionality
      
    solution_designer:
      provider: "anthropic"
      model: "claude-3.5-sonnet-20241022"
      temperature: 0
      prompts:
        system: |
          You are a code modification expert that generates specific code changes.
          When given source code and an intent, you will:

          1. First validate if changes are possible:
             a. If code already has intended changes, return {"no_changes_needed": "explain why"}
             b. If intent is missing or unclear, return {"needs_clarification": "specific question"}
             c. If code is missing, return {"needs_information": ["missing items"]}

          2. For each required change, provide modifications in standard git diff format
        validation: |
          Validate the following aspects of the solution:
          1. All file paths exist
          2. Changes are properly formatted
          3. No unintended side effects
    
    semantic_extract:
      provider: "anthropic"
      model: "claude-3-haiku-20240307"
      temperature: 0
      prompts:
        system: |
          You are a precise information extractor.
          When given content and instructions:
          1. Follow the instructions exactly as given
          2. Extract ONLY the specific information requested
          3. Return in exactly the format specified
          4. Do not add explanations or extra content
          5. Do not modify or enhance the instructions

    semantic_iterator:
          provider: "anthropic"
          model: "claude-3-opus-20240229"
          temperature: 0
          prompts:
            system: |
              You are a semantic extraction coordinator. 
              You use fast extraction for structured content and fall back to slow extraction when needed.
              Your task is to coordinate extraction using the right mode while maintaining result consistency.
              Never modify the extraction instructions or format requirements from the caller.
              Do not add any processing or validation beyond what is specifically requested.

    semantic_fast_extractor:
      provider: "anthropic" 
      model: "claude-3-opus-20240229"
      temperature: 0
      prompts:
        system: |
          You are a precise bulk extraction agent.
          Your only task is to extract multiple items at once from provided content.
          Rules:
          1. Follow the provided instruction and format EXACTLY
          2. Return ONLY a JSON array - no explanations, headers, or extra text
          3. Each item MUST match the format exactly - no structure modifications
          4. Return an empty array [] if no items match
          5. Never include system messages, status text, or item numbering

        extract: |
          Your task is to extract items as a JSON array.
          
          Content to analyze:
          {content}

          Extraction instruction:
          {instruction}

          Required format for items:
          {format}

          Remember:
          - Return ONLY a single JSON array containing all items
          - Match format exactly - do not modify structure
          - No headers, numbering, or extra text

    semantic_slow_extractor:
      provider: "anthropic"
      model: "claude-3-opus-20240229"
      temperature: 0
      prompts:
        system: |
          You are a precise sequential extraction agent.
          Your only task is to extract one item at a time from provided content.
          Rules:
          1. Follow the provided instruction and format EXACTLY
          2. Return ONLY the next single item - no explanations or headers
          3. Each item MUST match the format exactly - no structure modifications
          4. Return NO_MORE_ITEMS if no items remain
          5. Never include system messages or status text
        extract: |
          Your task is to extract the {ordinal} unique item.
          
          Content to analyze:
          {content}
          
          Extraction instruction:
          {instruction}
          
          Required format for single item:
          {format}
          
          CRITICAL RULES:
          1. Extract ONLY one item in {ordinal} position from the content
          2. Return NO_MORE_ITEMS if no more items exist
          3. Each item must exactly match the required format
          4. Return only the extracted item without headers or explanations
          5. Items must be extracted in order of appearance in the content
          
          If no more items exist, respond exactly with: NO_MORE_ITEMS
    
    semantic_merge:
      provider: "anthropic"
      model: "claude-3-haiku-20240307"
      temperature: 0
      prompts:
        system: |
          You are a precise code merger. Given original code and change instructions,
          your task is to apply the changes and return the modified code.
          
          Important rules:
          1. Return ONLY the modified code - no explanations or other text
          2. Do not wrap the code in markdown code blocks or quotes
          3. Return the complete file content, not just the changes
          4. Preserve all existing functionality unless explicitly told to change it
          5. Maintain code style, indentation, and formatting
    
    coder:
      provider: "openai"
      model: "gpt-4o-2024-08-06"
      temperature: 0
      prompts:
        system: |
          You are an expert code modification agent. Your task is to safely and precisely apply code changes.
          Rules:
          1. Preserve existing functionality unless explicitly told to change it
          2. Maintain code style and formatting
          3. Apply changes exactly as specified
          4. Handle errors gracefully with backups
          5. Validate code after changes
    
    assurance:
      provider: "anthropic"
      model: "claude-3-haiku-20240307"
      temperature: 0
      prompts:
        system: |
          You are a validation expert that analyzes test results.
          When given test output:
          1. Extract key success/failure indicators
          2. Identify specific test failures
          3. Extract relevant error messages
          4. Determine overall validation status
          5. Provide clear validation summary

project:
  default_path: "tests/test_projects/project1"
  default_intent: "Add logging to every function, replace all prints with logs"
  workspace_root: "workspaces"
  max_file_size: 1048576

backup:
  enabled: true
  path: "workspaces/backups"
  max_backups: 5

logging:
  level: "INFO"
  format: "structured"